### ISSUE TITLE
Inscopix -> CellReg data formatter

### ISSUE THREAD

**Issue by catubc** [zivlab/CellReg#13]
Here is some code to add to the helper directory for converting Inscopix 1P cell footprints to CellReg required format.

Thanks!

```


%% Converting the Inscopix .tif cell spatial footprints to input format for CellReg

clear all;

input_format='Inscopix'; %

%% Choosing the files for conversion:
%[file_names,files_path]=uigetfile('*.mat','MultiSelect','on',...
%    'Choose the spatial footprints from all the sessions: ' );
[files_path]=uigetdir('Choose the location of the footprints: ' );
file_names = dir(fullfile(files_path, '**', '*_CNMFe_CellSet_C*'));

%
this_session_num_cells = length(file_names);

% get size of footprints first
fname = file_names(1);
fname = fullfile(fname.folder, fname.name)
footprint = read(Tiff(fname,'r'));  

%
this_session_converted_footprints=zeros(this_session_num_cells,size(footprint, 1), size(footprint, 2));

%
for n=1:this_session_num_cells

    fname = file_names(n);
    fname = fullfile(fname.folder, fname.name);
    
    %
    footprint = read(Tiff(fname,'r'));    
    this_session_converted_footprints(n,:,:)= footprint;
    
end
fname_out = fullfile(file_names(1).folder, 'converted.mat');
save(fname_out,'this_session_converted_footprints','-v7.3')



```

**Comment by Sheintuch** [comment]
This is great! Thanks.
Can you send me example footprints (from at least two sessions) so I can test it?
In addition, you can use 'git push' to add your specific change to the code and then I can merge the pull request.
This will also add your git account as a contributor to CellReg.
But if you so, please only add this change to the code and not other unrelated changes.

**Comment by catubc** [comment]
Ok, great, pull request is in. I also put some test data in the cloud, but it's also linked in the pull request

https://drive.google.com/file/d/1mpREe3AK54ZOhQJ3_3CMWs0txyaRRSIS/view?usp=sharing

For now, the results on the Inscopix CNMF-E footprints looks pretty good, but not as good as the Suite2p data. I assume that even though the contour plots don't overlap as well for the CNMF-E data, they were still good matches in the CellReg algorithms.

![thresh65_laurenz](https://user-images.githubusercontent.com/4267452/152174694-dd6e1d48-0053-43b5-9a5e-d7f4642d9abc.png)

**Comment by Sheintuch** [comment]
Great. I tested the code and merged your pull request.
Thanks!
