### ISSUE TITLE
Fuzzy Logic Toolbox required (?)

### ISSUE THREAD

**Issue by AthenaIak** [zivlab/CellReg#2]
Hello, 

When I run the model computation, it crashes at

https://github.com/zivlab/CellReg/blob/33ea8306217e71a286a094174fa09acbeb8e5e63/CellReg/compute_spatial_correlations_model.m#L54

The error message I get is

> To use 'sigmf', you might need:
>  sigmf - Fuzzy Logic Toolbox

Given that this add-on is not free, I tried to define my own function 
`sigmf = @(x,ac) 1./(1+exp(-ac(1)*(x-ac(2))));`

Now it no longer crashes and everything seems fine. Could you maybe verify that the output is exactly the same? 

Thank you for sharing this!

**Comment by Sheintuch** [comment]
Hi,

The output that is obtained by the sigmf function you defined is exactly the same.
I will change this line in the code to the function you defined in the next CellReg release - v1.1.7
Thank you for noting to this problem!
