### ISSUE TITLE
3 Errors on Linux

### ISSUE THREAD

**Issue by Mraymon5** [zivlab/CellReg#21]
OS: Ubuntu 24.04
Matlab: 2024a
Cellreg: 1.5.7

Running: /CellReg/GUI/CellReg.m

I did also run CellReg_setup.m before running anything else.

I've run into 3 different errors running CellReg on my Ubuntu machine, and I think I have fixes for all 3, at least for my system.

**Fatal Bug:**
On running stage 2 (FOV allignment), it seems to successfully run the analysis, and prints the resulting figure, but also throws this error:
```Warning: Variable 'hgS_070000' was not saved. For variables larger than 2GB use MAT-file version 7.3 or later.```
And then stage 3 won't run.

With this traceback to a read-only file:
```> In matlab.graphics.internal.figfile.FigFile/write (line 33)```
Corresponding to the line:
```save(obj.Path, obj.MatVersion, '-struct', 'SaveVars');```

I ran CellReg again as Sudo, and changed that line to:
```save(obj.Path, obj.MatVersion, '-struct', 'SaveVars', '-v7.3');```

I also added the same argument to line 1261 of /GUI/CellReg.m, changing:
```save(fullfile(results_directory,f_name),'footprint');```
to
```save(fullfile(results_directory,f_name),'footprint','-v7.3');```

Which seemed to solve the problem.

**Bug Saving Figures:**
I also run into an issue saving figures in steps 1 and 3. 
/CellReg/plot_models.m (line 125)
/CellReg/plot_all_sessions_projections.m (line 37)

Both of these calls to savefig() create weird behavior; they pull focus away from the intended target figures, and back to the GUI. This means that both "Stage 1 - spatial footprints projections.fig" and "Stage 3 - model.fig" are just the CellReg GUI instead of the intended figures. This has the downstream effect that the saveas() calls that immediately follow the savefig() calls are saving the gui also. I tried changing the savefig() call to include gcf (i.e. ```savefig(gcf, FileName)```), and this successfully forced savefig() to save the target figure instead of the GUI, but then still pulls focus to the GUI and results in the .png files from the saveas() calls just being images of the GUI. So ultimately my solution was to add a line before savefig() that stores the target figure address, and to call that address in both savefig() and saveas():
```
ModelFig = gcf;
savefig(ModelFig,fullfile(figures_directory,'Stage 3 - model.fig')) %Culprit, this is pulling focus to the gui
saveas(ModelFig,fullfile(figures_directory,'Stage 3 - model'),'png') %Targeting ModelFig specifically
```
for plot_models.m and
```
FP_Fig = gcf
savefig(FP_Fig, fullfile(figures_directory,'Stage 1 - spatial footprints projections.fig'))
saveas(FP_Fig,fullfile(figures_directory,'Stage 1 - spatial footprints projections'),'png')
```
for plot_all_sessions_projections.m
Making those edits has fixed that problem for me.

**Annoying Warning:**
On running stage 3, I get this warning:
```Warning: Colon operands must be real scalars. This warning will become an error in a future release.```
With a traceback to:
```> In compute_spatial_correlations_model (line 97)```
Corresponding to:
```spatial_correlations_model_same_cells(1:round(number_of_bins/10:end))=0;```

Based on the suggestion of ChatGPT, I changed that line to:
```
array_length = length(spatial_correlations_model_same_cells);
indices = 1:round(number_of_bins/10):array_length;
spatial_correlations_model_same_cells(indices) = 0;
```

Which seems to have gotten rid of that warning and hasn't otherwise changed the behavior of CellReg (I still got the same # of cells on initial registration)

**Comment by Mraymon5** [comment]
The plotting problem also just popped up on plot_alignment_results.m (line 100), and I was able to fix it the same way. It seems like this might be a problem on and off any time that savefig() is used?

**Comment by Sheintuch** [comment]
Are these errors due to running CellReg on Ubuntu machine? Are you registering the sample data or your own data?
If you run CellReg on the same data with a windows OS you don't encounter the same errors?

If this is indeed a Ubuntu issue, would you like to add a pull request for your fixes of the code and I can update CellReg accordingly?

**Comment by Mraymon5** [comment]
I was previously using CellReg on a Windows machine, and I don't recall having any of those issues. It's possible the "colon operand" error was present, and I just didn't notice it, but the other two have sufficient performance impacts that I would have noticed.

I haven't tried it with the sample data yet: let me check that out and report back.

**Comment by Sheintuch** [comment]
Thank you for all the detailed description of the error and fixes.
The correct function of this line of code should be to set the first 10% of 'spatial_correlations_model_same_cells' to 0.
