### ISSUE TITLE
step 3 "compute model" error 

### ISSUE THREAD

**Issue by wenyu-ding** [zivlab/CellReg#23]
Hello,

I'm using “format_conversion_inscopix.m" to convert my tiff into spacitial data, then run cellReg.m. It was doing good before step 3 "compute model", see below my results:
![image](https://github.com/user-attachments/assets/2e36001d-26f7-411a-81a1-2bed7c2ac308)
but when i run step 3, it comes error, see below:

Error using lsqncommon
Objective function is returning Inf or NaN values at initial point. lsqcurvefit
cannot continue.

Error in lsqcurvefit (line 274)
    lsqncommon(funfcn,xCurrent,lb,ub,options,defaultopt,optimgetFlag,caller,...

Error in compute_centroid_distances_model (line 53)
centroid_distances_model_parameters=lsqcurvefit(F,initial_parameters,microns_per_pixel*centroid_distances_centers,centroid_distances_distribution,lb,ub,options);

Error in CellReg>compute_model_Callback (line 930)
    compute_centroid_distances_model(neighbors_centroid_distances,microns_per_pixel,centers_of_bins);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('compute_model_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Can you give me some suggestions how to solve it? thank you very much!

**Comment by Sheintuch** [comment]
Hi, can tell me which CellReg version you were running?
If it was not the most up to date (v1.5.9), first change the version and try to run CellReg again.
If that doesn't work, you can send me via email the data you are using as an input for CellReg (after the conversion) and I will try to run the code and see what is causing the error.

**Comment by wenyu-ding** [comment]
thank you so much for the quick reply. I'm using the latest version (v1.5.9). see below 
![image](https://github.com/user-attachments/assets/04505f06-95e5-4adf-82f2-5a4320a47d3e)
I will send you my data by email. Thanks for your help!

**Comment by wenyu-ding** [comment]
Hi, please find my converted data in the attached files.
in case i did something wrong, i also attached my original tiff from
inscopix. Since every tiff has different dimensions, I was using Fiji to
convert them and make them brighter.
Let me know if you need to know anything else. Thank you very much!

Best,
Wenyu

Liron Sheintuch ***@***.***> 于2024年11月12日周二 21:03写道：

**Comment by Sheintuch** [comment]
Hi Wenyu, I don't see the files in the email. 
Can you please send a separate email to lironsheintuch@gmail.com with the files?

**Comment by Sheintuch** [comment]
The data the you sent me (c_converted, e_converted, s_converted) are a single image with the projection of all cells from each sessions onto that image (size MxK, where M is the number of pixels in the y axis and K is the number of pixels in the x axis). This is not the correct format CellReg requires as an input. What you need to obtain is a matrix for each each session of size NxMxK, where N is the number of neurons, M is the number of pixels in the y axis and K is the number of pixels in the x axis. 

You are welcome to join our slack channel where you might find more helpful information on how to work with CellReg.

**Comment by Sheintuch** [comment]
I am closing this issue. We can continue our communication on how to properly use CellReg in the slack channel.

**Comment by wenyu-ding** [comment]
Hi Liron,

Please find my data in the attached file. There are 10 sessions. Could you
let me know how to get the best registration.Thank you very much!

Best,
Wenyu

Liron Sheintuch ***@***.***> 于2024年11月14日周四 23:27写道：
