### ISSUE TITLE
Joint distance-corr model

### ISSUE THREAD

**Issue by noahpettit** [zivlab/CellReg#3]
Hi,
Does this repository contain code for doing probabilistic registration using the "joint" model? In my dataset, spatial correlation (of cell masks aligned to one another, so slightly different from what you've done) and centroid distance both seem to carry quite a bit of information about which cells are the same (based on visual inspection of the joint distribution). In the paper it looks to me like the joint model tends to do better than the single-variable models, but I can't seem to find the implementation of it in this code - it looks like I have to pick either "centroid distance" or "spatial correlation". 
Any help/clarification would much appreciated! And thanks so much for sharing your code!

**Comment by Sheintuch** [comment]
Hi Noah, 
The repository does not contain the code for the joint probabilistic model.
After comparing between the different models, we found that the joint model added only a little to the potential accuracy of cell registration. However, the 2D joint model has many more parameters compared to the 1D centroid distances or spatial correlations models, and therefore it is much more prone to overfitting. For that reason we decided it would be overall more reliable to use the 1D models compared to the 2D, and we did not put the code for the joint model to avoid its misuse. That said, it might be interesting to try and develop a new joint model with less parameters that might improve registration accuracy even further.

**Comment by noahpettit** [comment]
Hi,
Thanks so much for your reply. That makes sense. Maybe one approach could be to use the first PC in the 2d distance-corr space as a "similarity" measure to get an axis that incorporates a bit of information about both distance and correlation, on which your method could be applied?   
That being said, I am having fairly good results with a distance-only model, so I will stick with that for now! Thanks again for the clarification.
