### ISSUE TITLE
Problems saving 'Stage 3 - model.fig'

### ISSUE THREAD

**Issue by obarnstedt** [zivlab/CellReg#4]
Hi and thanks for the great toolbox! I have found it very useful for our data.

Unfortunately, I keep running into an error that suggests Matlab has problems saving 'Stage 3 -model.fig', and I am not entirely sure why this should pose a problem as the other .fig files are saved properly, and the problem only occurs with some data sets. If I comment out the line containing savefig, the problem vanishes. This is with Matlab R2019b Update 1 (9.7.0.1216025) under glnxa64 (Linux).
Please find the full error message below.

Thanks for the great work!
Oliver

```
Stage 3 - Calculating a probabilistic model of the data
Calculating the distributions of cell-pair similarities:
Calculating spatial correlations and centroid distances for session #1 - 100%    [..........] done
Calculating spatial correlations and centroid distances for session #2 - 100%    [..........] done
Calculating a probabilistic model of the data

Local minimum possible.

lsqcurvefit stopped because the final change in the sum of squares relative to 
its initial value is less than the value of the function tolerance.

<stopping criteria details>
Warning: There is large discrepancy between the centroid distances model and the
data 
> In choose_best_model (line 51)
  In CellReg>compute_model_Callback (line 925)
  In gui_mainfcn (line 95)
  In CellReg (line 85)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('compute_model_Callback',hObject,eventdata,guidata(hObject)) 
Warning: Variable 'hgS_070000' was not saved. For variables larger than 2GB use
MAT-file version 7.3 or later. 
> In matlab.graphics.internal.figfile.FigFile/write (line 32)
  In savefig (line 83)
  In plot_models (line 121)
  In CellReg>compute_model_Callback (line 947)
  In gui_mainfcn (line 95)
  In CellReg (line 85)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('compute_model_Callback',hObject,eventdata,guidata(hObject)) 
Error using save
Error closing file
/groups/ag-remy-2/Imaging/OB/Results/139_140_141_142_143_144_145_146_147_148/CellReg/Figures/Stage
3 - model.fig.
The file may be corrupt.

Error in matlab.graphics.internal.figfile.FigFile/write (line 32)
save(obj.Path, obj.MatVersion, '-struct', 'SaveVars');

Error in savefig (line 83)
FF.write();

Error in plot_models (line 121)
savefig(fullfile(figures_directory,'Stage 3 - model.fig'))

Error in CellReg>compute_model_Callback (line 947)
    plot_models(centroid_distances_model_parameters,NN_centroid_distances,NNN_centroid_distances,centroid_distances_distribution,centroid_distances_model_same_cells,centroid_distances_model_different_cells,centroid_distances_model_weighted_sum,centroid_distance_intersection,centers_of_bins,microns_per_pixel,normalized_maximal_distance,figures_directory,figures_visibility)

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('compute_model_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

**Comment by Sheintuch** [comment]
Hi Oliver,
Thank you for writing about this issue.
Does the same error occur for different data sets?
Does it also happen if you use a different MATLAB version?

**Comment by obarnstedt** [comment]
Hi Liron,
thanks for your quick reply!
I was just testing this under different conditions. Interestingly enough, the error vanished when I ran the same dataset again under the same conditions, after uncommenting the 'savefig' line again. The next experiment worked fine, then the error appeared again on the next one, and persisted. I just switched to Matlab R2016a, with similar results. Same error with 'savefig'; now I deleted the 1kb 'Stage 3 -model.fig' file, ran it again after loading the aligned data set, and it passed fine. This seems to appear only(?) with non-rigidly registered data. It's a bit puzzling...

**Comment by Sheintuch** [comment]
I agree that this is puzzling. 
Did you run the CellReg process from the beginning to the end in one time?
Because I remember there was a problem once if for example you would start the registration procedure and stopped after the alignment step. Then if you changed the directories and continued from that point (using the load aligned data) you could have gotten an error because it did not update correctly the path for the figures/results folders. 

Could this be the case here?
