### ISSUE TITLE
GUI Malfunction 

### ISSUE THREAD

**Issue by palpareek** [zivlab/CellReg#6]
Hey! 

I have been trying to use the GUI but it has been showing me a lot of errors when I try to run the sample data provided with the repo code. The same errors occur when I am trying to run the Sample Data through the demo file on MATLAB. It loads up the figure at Stage 1 but begins showing errors midway through Stage 2. 

I am posting the errors. Your help and support are greatly appreciated. 

>> CellReg
Stage 1 - Loading sessions
Calculating spatial footprints projections:
Calculating footprints projections for session #1 - 100%    [..........] done
Calculating footprints projections for session #2 - 100%    [..........] done
Calculating footprints projections for session #3 - 100%    [..........] done
Calculating footprints projections for session #4 - 100%    [..........] done
Calculating footprints projections for session #5 - 100%    [..........] done
Done
Stage 2 - Aligning sessions
Normalizing spatial footprints:
Normalizing spatial footprints for session #1 - 100%    [..........] done
Normalizing spatial footprints for session #2 - 100%    [..........] done
Normalizing spatial footprints for session #3 - 100%    [..........] done
Normalizing spatial footprints for session #4 - 100%    [..........] done
Normalizing spatial footprints for session #5 - 100%    [..........] done
Calculating spatial footprints projections:
Calculating footprints projections for session #1 - 100%    [..........] done
Calculating footprints projections for session #2 - 100%    [..........] done
Calculating footprints projections for session #3 - 100%    [..........] done
Calculating footprints projections for session #4 - 100%    [..........] done
Calculating footprints projections for session #5 - 100%    [..........] done
Calculating centroid locations:
Calculating centroid locations for session #1 - 100%    [..........] done
Calculating centroid locations for session #2 - 100%    [..........] done
Calculating centroid locations for session #3 - 100%    [..........] done
Calculating centroid locations for session #4 - 100%    [..........] done
Calculating centroid locations for session #5 - 100%    [..........] done
Aligning session #2:
Checking for rotations
Error using align_images (line 126)
Undefined function 'normxcorr2' for input arguments of type 'double'.

Error in CellReg>transform_sessions_Callback (line 707)
        align_images(adjusted_spatial_footprints,centroid_locations,adjusted_footprints_projections,centroid_projections,adjusted_FOV,microns_per_pixel,reference_session_index,alignment_type,sufficient_correlation_centroids,sufficient_correlation_footprints,use_parallel_processing,maximal_rotation);
        
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('transform_sessions_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by Sheintuch** [comment]
Hi,
Which version of Matlab are you using?
Which version of CellReg are you using?
Did you set up the repository as specified in the 'README.md' file?

**Comment by palpareek** [comment]
The MATLAB version I have been using is 2018a. While I was able to switch to the v1.3.7 after seeing your comment and following the instructions on the README.md file, I have been getting even more errors ever since I switched to this CellReg version. 

>> CellReg
Brace indexing is not supported for variables of this type.

Error in CellReg>load_new_data_Callback (line 224)
    sessions_list{1,n}=['Session ' num2str(n) ' - ' files_path file_names{1,n}];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('load_new_data_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Stage 1 - Loading sessions
Calculating spatial footprints projections:
Calculating footprints projections for session #1 - 100%    [..........] done
Calculating footprints projections for session #2 - 100%    [..........] done
Calculating footprints projections for session #3 - 100%    [..........] done
Calculating footprints projections for session #4 - 100%    [..........] done
Calculating footprints projections for session #5 - 100%    [..........] done
Reference to non-existent field 'number_of_sessions'.

Error in CellReg>transform_sessions_Callback (line 632)
number_of_sessions=data_struct.number_of_sessions;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('transform_sessions_Callback',hObject,eventdata,guidata(hObject)) 
Error using print (line 36)
Error while evaluating UIControl Callback.

Done
Stage 2 - Aligning sessions
Normalizing spatial footprints:
Normalizing spatial footprints for session #1 - 100%    [..........] done
Normalizing spatial footprints for session #2 - 100%    [..........] done
Normalizing spatial footprints for session #3 - 100%    [..........] done
Normalizing spatial footprints for session #4 - 100%    [..........] done
Normalizing spatial footprints for session #5 - 100%    [..........] done
Calculating spatial footprints projections:
Calculating footprints projections for session #1 - 100%    [..........] done
Calculating footprints projections for session #2 - 100%    [..........] done
Calculating footprints projections for session #3 - 100%    [..........] done
Calculating footprints projections for session #4 - 100%    [..........] done
Calculating footprints projections for session #5 - 100%    [..........] done
Calculating centroid locations:
Calculating centroid locations for session #1 - 100%    [..........] done
Calculating centroid locations for session #2 - 100%    [..........] done
Calculating centroid locations for session #3 - 100%    [..........] done
Calculating centroid locations for session #4 - 100%    [..........] done
Calculating centroid locations for session #5 - 100%    [..........] done
Aligning session #2:
Checking for rotations
Error using align_images (line 126)
Undefined function 'normxcorr2' for input arguments of type 'double'.

Error in CellReg>transform_sessions_Callback (line 707)
        align_images(adjusted_spatial_footprints,centroid_locations,adjusted_footprints_projections,centroid_projections,adjusted_FOV,microns_per_pixel,reference_session_index,alignment_type,sufficient_correlation_centroids,sufficient_correlation_footprints,use_parallel_processing,maximal_rotation);
        
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in CellReg (line 85)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CellReg('transform_sessions_Callback',hObject,eventdata,guidata(hObject)) 
Error using matlab.ui.internal.legacyMoveGUI (line 15)
Error while evaluating UIControl Callback.

**Comment by Sheintuch** [comment]
I've never encountered these errors.
Did you run the 'setup.m' script (which adds folders with the relevant scripts to the Matlab path) prior to the cell registration procedure? 
Can you try running CellReg with a different Matlab version or from a different computer and see if you get the same errors?

If these errors occur when running the sample data then this cannot be a complicated problem, since we know that CellReg works properly for this data set exactly. So it must be some kind of problem with versioning of CellReg/Matlab or definition of paths, or something related.
