### ISSUE TITLE
Matlab R2020b lsqcurvefit syntax

### ISSUE THREAD

**Issue by madeleinesnyder** [zivlab/CellReg#8]
Hi, using CellReg in Matlab2020b, I noticed an error that occurs as a results of the lsqcurvefit syntax. The options.algorithm field isn't created in the struct that the new lsqnsetup function requires. To get around this i just defined options.algorithm = [] before the call to lsqcurvefit and it worked.

**Comment by Sheintuch** [comment]
Hi, thanks for opening this issue. 
I added the 'options.algorithm = []' code before using the 'lsqcurvefit' function as you suggested. 
This is now fixed in CellReg version v1.4.1.

**Comment by Sheintuch** [comment]
Hi, thanks for finding this issue and its solution.
I changed the 'options.algorithm = []' to 'options.Algorithm = []'  as you suggested.
This is now fixed in CellReg version v1.4.6.
